export const SET_CURRENT_USER='SET_CURRENT_USER';
export const GET_ERRORS='GET_ERRORS';
export const ADD_EXPENSE='ADD_EXPENSE';
export const READ_EXPENSE='READ_EXPENSE';
export const UPDATE_EXPENSE='UPDATE_EXPENSE';
export const DELETE_EXPENSE='DELETE_EXPENSE';
